#!/usr/bin/env python3

import sys
import math

def factorize(n):
    for j in range(2, int(math.sqrt(n))+1):
        if n % j == 0:
            return j, n//j
    return None, None

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

filename = sys.argv[1]

try:
    with open(filename, 'r') as f:
        for line in f:
            n = int(line.strip())
            p, q = factorize(n)
            print("{}={}*{}".format(n, p, q))
except IOError:
    print("Error: Could not read file", filename)
    sys.exit(1)
